### ISSUE TITLE
viz_tests failed

### ISSUE THREAD

**Issue by lbazan** [ResidentMario/missingno#85]
test_log_bar (viz_tests.TestBar) ... ERROR
test_simple_bar (viz_tests.TestBar) ... ERROR
test_method_dendrogram (viz_tests.TestDendrogram) ... ERROR
test_orientation_dendrogram (viz_tests.TestDendrogram) ... ERROR
test_simple_dendrogram (viz_tests.TestDendrogram) ... ERROR
test_geoplot_quadtree (viz_tests.TestGeoplot) ... ERROR
test_alternative_colormap_heatmap (viz_tests.TestHeatmap) ... ERROR
test_simple_heatmap (viz_tests.TestHeatmap) ... ERROR
test_unlabelled_heatmap (viz_tests.TestHeatmap) ... ERROR
test_color_matrix (viz_tests.TestMatrix) ... ERROR
test_fontsize_matrix (viz_tests.TestMatrix) ... ERROR
test_freq_matrix (viz_tests.TestMatrix) ... ERROR
test_large_matrix (viz_tests.TestMatrix) ... ERROR
test_no_sparkline_matrix (viz_tests.TestMatrix) ... ERROR
test_simple_matrix (viz_tests.TestMatrix) ... ERROR
test_width_ratios_matrix (viz_tests.TestMatrix) ... ERROR

======================================================================
ERROR: test_log_bar (viz_tests.TestBar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 76, in test_log_bar
    msno.bar(self.simple_df, log=True)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 217, in bar
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_simple_bar (viz_tests.TestBar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 71, in test_simple_bar
    msno.bar(self.simple_df)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 217, in bar
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_method_dendrogram (viz_tests.TestDendrogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 123, in test_method_dendrogram
    msno.dendrogram(self.simple_df, method='single')
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 372, in dendrogram
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_orientation_dendrogram (viz_tests.TestDendrogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 118, in test_orientation_dendrogram
    msno.dendrogram(self.simple_df, orientation='right')
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 372, in dendrogram
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_simple_dendrogram (viz_tests.TestDendrogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 113, in test_simple_dendrogram
    msno.dendrogram(self.simple_df)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 372, in dendrogram
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_geoplot_quadtree (viz_tests.TestGeoplot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 139, in test_geoplot_quadtree
    msno.geoplot(self.x_y_df, x='r0', y='r1')
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 482, in geoplot
    gplt.aggplot(gdf, figsize=figsize, hue='nullity', agg=np.average, cmap=cmap, by=by, edgecolor='None', **kwargs)
  File "/usr/lib/python3.7/site-packages/geoplot/geoplot.py", line 866, in aggplot
    fig = _init_figure(ax, figsize)
  File "/usr/lib/python3.7/site-packages/geoplot/geoplot.py", line 2188, in _init_figure
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
-------------------- >> begin captured logging << --------------------
shapely.geos: DEBUG: Trying `CDLL(libgeos_c.so.1)`
shapely.geos: DEBUG: Library path: 'libgeos_c.so.1'
shapely.geos: DEBUG: DLL: <CDLL 'libgeos_c.so.1', handle 5638a10ece60 at 0x7f47c62ebb00>
shapely.geos: DEBUG: Trying `CDLL(libc.so.6)`
shapely.geos: DEBUG: Library path: 'libc.so.6'
shapely.geos: DEBUG: DLL: <CDLL 'libc.so.6', handle 7f47ee2a18b0 at 0x7f47c62eb518>
fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x7f47b41f57f0>
fiona.env: DEBUG: Starting outermost env
fiona.env: DEBUG: No GDAL environment exists
fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x7f47b41f5860> created
fiona._env: DEBUG: Logging error handler pushed.
fiona._env: DEBUG: All drivers registered.
fiona._env: DEBUG: GDAL_DATA not found in environment, set to '/usr/share/gdal'.
fiona._env: DEBUG: PROJ data not found in environment, set to '/usr/share/proj'.
fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x7f47b41f5860>.
fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x7f47b41f5860> with options {}
fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x7f47b41f57f0>
fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x7f47b41f57f0>
fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x7f47b41f5860> options
fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x7f47b41f5860>.
fiona._env: DEBUG: Error handler popped.
fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x7f47b41f5860>.
fiona.env: DEBUG: Exiting outermost env
fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x7f47b41f57f0>
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_alternative_colormap_heatmap (viz_tests.TestHeatmap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 98, in test_alternative_colormap_heatmap
    msno.heatmap(self.simple_df, cmap='viridis')
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 291, in heatmap
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_simple_heatmap (viz_tests.TestHeatmap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 88, in test_simple_heatmap
    msno.heatmap(self.simple_df)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 291, in heatmap
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_unlabelled_heatmap (viz_tests.TestHeatmap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 93, in test_unlabelled_heatmap
    msno.heatmap(self.simple_df, labels=False)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 291, in heatmap
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_color_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 45, in test_color_matrix
    msno.matrix(self.simple_df, color=(70 / 255, 130 / 255, 180 / 255))
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_fontsize_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 50, in test_fontsize_matrix
    msno.matrix(self.simple_df, fontsize=8)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_freq_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 55, in test_freq_matrix
    msno.matrix(self.freq_df, freq='BQ')
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_large_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 60, in test_large_matrix
    msno.matrix(self.large_df)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_no_sparkline_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 35, in test_no_sparkline_matrix
    msno.matrix(self.simple_df, sparkline=False)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_simple_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 30, in test_simple_matrix
    msno.matrix(self.simple_df)
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

======================================================================
ERROR: test_width_ratios_matrix (viz_tests.TestMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/tests/viz_tests.py", line 40, in test_width_ratios_matrix
    msno.matrix(self.simple_df, width_ratios=(30, 1))
  File "/home/lbazan/rpmbuild/BUILD/missingno-0.4.0/missingno/missingno.py", line 51, in matrix
    fig = plt.figure(figsize=figsize)
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib64/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

----------------------------------------------------------------------
Ran 26 tests in 1.056s

**Comment by ResidentMario** [comment]
This is a `matplotlib` issue, not a `missingno` one. Please see the instructions on setting up your display backend in `matplotlib`, or [this StackOverflow answer](https://stackoverflow.com/a/37605654/1993206) talking about this exact specific error.

**Comment by lbazan** [comment]
thanks! 

Cheers,

**Comment by lbazan** [comment]
@ResidentMario 

Can you help with this?

BUILDSTDERR: ERROR: test_geoplot_quadtree (viz_tests.TestGeoplot)
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILD/missingno-0.4.0/tests/viz_tests.py", line 139, in test_geoplot_quadtree
BUILDSTDERR:     msno.geoplot(self.x_y_df, x='r0', y='r1')
BUILDSTDERR:   File "/builddir/build/BUILD/missingno-0.4.0/missingno/missingno.py", line 454, in geoplot
BUILDSTDERR:     import geoplot as gplt
BUILDSTDERR:   File "/usr/lib/python3.7/site-packages/geoplot/__init__.py", line 1, in <module>
BUILDSTDERR:     from .geoplot import (pointplot, polyplot, choropleth, aggplot, cartogram, kdeplot, sankey, voronoi,
BUILDSTDERR:   File "/usr/lib/python3.7/site-packages/geoplot/geoplot.py", line 15, in <module>
BUILDSTDERR:     import descartes
BUILDSTDERR: ModuleNotFoundError: No module named 'descartes'
BUILDSTDERR: -------------------- >> begin captured logging << --------------------
BUILDSTDERR: shapely.geos: DEBUG: Trying `CDLL(libgeos_c.so.1)`
BUILDSTDERR: shapely.geos: DEBUG: Library path: 'libgeos_c.so.1'
BUILDSTDERR: shapely.geos: DEBUG: DLL: <CDLL 'libgeos_c.so.1', handle 56276971be60 at 0x7f4898b11e80>
BUILDSTDERR: shapely.geos: DEBUG: Trying `CDLL(libc.so.6)`
BUILDSTDERR: shapely.geos: DEBUG: Library path: 'libc.so.6'
BUILDSTDERR: shapely.geos: DEBUG: DLL: <CDLL 'libc.so.6', handle 7f48b99bf000 at 0x7f4898b11898>
BUILDSTDERR: fiona.env: DEBUG: GDAL data files are available at built-in paths
BUILDSTDERR: fiona.env: DEBUG: PROJ data files are available at built-in paths
BUILDSTDERR: fiona.env: DEBUG: Entering env context: <fiona.env.Env object at 0x7f489d0a7ba8>
BUILDSTDERR: fiona.env: DEBUG: Starting outermost env
BUILDSTDERR: fiona.env: DEBUG: No GDAL environment exists
BUILDSTDERR: fiona.env: DEBUG: New GDAL environment <fiona._env.GDALEnv object at 0x7f489d0a7c18> created
BUILDSTDERR: fiona._env: DEBUG: Logging error handler pushed.
BUILDSTDERR: fiona._env: DEBUG: All drivers registered.
BUILDSTDERR: fiona._env: DEBUG: GDAL data files are available at built-in paths
BUILDSTDERR: fiona._env: DEBUG: PROJ data files are available at built-in paths
BUILDSTDERR: fiona._env: DEBUG: Started GDALEnv <fiona._env.GDALEnv object at 0x7f489d0a7c18>.
BUILDSTDERR: fiona.env: DEBUG: Updated existing <fiona._env.GDALEnv object at 0x7f489d0a7c18> with options {}
BUILDSTDERR: fiona.env: DEBUG: Entered env context: <fiona.env.Env object at 0x7f489d0a7ba8>
BUILDSTDERR: fiona.env: DEBUG: Exiting env context: <fiona.env.Env object at 0x7f489d0a7ba8>
BUILDSTDERR: fiona.env: DEBUG: Cleared existing <fiona._env.GDALEnv object at 0x7f489d0a7c18> options
BUILDSTDERR: fiona._env: DEBUG: Stopping GDALEnv <fiona._env.GDALEnv object at 0x7f489d0a7c18>.
BUILDSTDERR: fiona._env: DEBUG: Error handler popped.
BUILDSTDERR: fiona._env: DEBUG: Stopped GDALEnv <fiona._env.GDALEnv object at 0x7f489d0a7c18>.
BUILDSTDERR: fiona.env: DEBUG: Exiting outermost env
BUILDSTDERR: fiona.env: DEBUG: Exited env context: <fiona.env.Env object at 0x7f489d0a7ba8>
BUILDSTDERR: --------------------- >> end captured logging << ---------------------
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Ran 26 tests in 2.636s
BUILDSTDERR: FAILED (errors=1)
